name: Automated PR Review with Manual Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prepare-review:
    runs-on: ubuntu-latest
    outputs:
      review_comments: ${{ steps.collect.outputs.review_comments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: repo
      - name: Run PR Review Bot (Collect Comments)
        id: collect
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          node repo/pr-review.js --collect-comments > review-comments.json
          echo "review_comments=$(cat review-comments.json | jq -c .)" >> $GITHUB_OUTPUT
      - name: Upload Review Comments Artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-comments
          path: review-comments.json

  manual_request_changes:
    runs-on: ubuntu-latest
    needs: prepare-review
    environment:
      name: request-changes-approval
      # reviewers: [sofikul-dev] # Optional: require specific reviewers
    steps:
      - name: Download Review Comments Artifact
        uses: actions/download-artifact@v4
        with:
          name: review-comments
      - name: Display Review Comments
        run: cat review-comments.json
      - name: Wait for manual approval
        run: echo "Waiting for reviewer to approve or modify review comments."

  post-request-changes:
    runs-on: ubuntu-latest
    needs: manual_request_changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Install dependencies
        run: npm install
        working-directory: repo
      - name: Download Review Comments Artifact
        uses: actions/download-artifact@v4
        with:
          name: review-comments
      - name: Post Review Comments
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node repo/pr-review.js --post-comments review-comments.json

  manual_approve:
    runs-on: ubuntu-latest
    needs: post-request-changes
    environment:
      name: approve-approval
      # reviewers: [sofikul-dev] # Optional: require specific reviewers
    steps:
      - name: Wait for manual approval to approve PR
        run: echo "Waiting for reviewer to approve PR."

  approve:
    runs-on: ubuntu-latest
    needs: manual_approve
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Install dependencies
        run: npm install
        working-directory: repo
      - name: Approve PR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node repo/pr-review.js --approve
